# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        auth_token_user_provider:
            id: auth_token_user_provider
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            stateless: true
            provider: auth_token_user_provider
            anonymous: ~

     # Ajout d'un encoder pour notre entité User
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
