AppBundle\Entity\Country:
    exclusion_policy: none
    properties:
        id:
            expose: true
            groups : [Details]
        code:
            expose: true
        label:
            expose: true
